#
# Boosters
# by Auxilor
#

# Even if eco is set up to use a database, you can
# force Boosters to save to local storage to disable
# cross-server sync.
use-local-storage: false

gui:
  title: Boosters (%page%/%max_page%) # Supports %page% and %max_page% placeholders.
  rows: 3 # The amount of rows to have (1-6).

  # Sound played when the page turns.
  sound:
    enabled: true
    sound: ui.button.click
    pitch: 1.0
    volume: 1.0

  # Navigation options. Shows the inactive item on the first/last page, or hides
  # the button when no item-inactive is set.
  forwards-arrow:
    item: arrow name:"&fNext Page"
    item-inactive: gray_dye name:"&7Next Page"
    row: 3
    column: 6
  backwards-arrow:
    item: arrow name:"&fPrevious Page"
    item-inactive: gray_dye name:"&7Previous Page"
    row: 3
    column: 4

  # Add as many pages as you want by appending to this list.
  pages:
    - page: 1
      mask:
        items:
          - black_stained_glass_pane
        pattern:
          - "111111111"
          - "101101101"
          - "111111111"
      # Custom GUI slots; see here: https://plugins.auxilor.io/all-plugins/custom-gui-slots
      custom-slots: []

sounds:
  activate:
    enabled: true
    sound: ENTITY_PLAYER_LEVELUP
    volume: 2
    pitch: 0.9
    category: AMBIENT
  increment:
    enabled: true
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 2
    pitch: 0.9
    category: AMBIENT
  expire:
    enabled: true
    sound: ENTITY_ITEM_BREAK
    volume: 2
    pitch: 0.9
    category: AMBIENT