#
# Boosters
# by Auxilor
#

gui:
  title: Boosters
  rows: 3
  mask:
    items:
      - black_stained_glass_Pane
    pattern:
      - "111111111"
      - "101101101"
      - "111111111"

cooldown:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

cannot-afford:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

cannot-afford-type:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

point-names: # If you have point names that look ugly (eg g_souls) then you can map them to nice names to be shown to players.
  example_point: "Nicely Formatted Point"

use-faster-move-trigger: true # Disable if you want move trigger to detect sub-1-block movements
raytrace-distance: 80 # The distance that alt_click should check for a location
block-item-drop-place-check: true # If the block_item_drop trigger should only fire on naturally placed blocks (prevents dupes)

potions:
  icon:
    permanent: true
    triggered: true
  ambient:
    permanent: false
    triggered: true
  particles:
    permanent: false
    triggered: true

share-configs: true # If your configs are allowed to be used to gather data and improve the plugin. Nothing identifying (IP, Name, etc) is shared.
